@@include('files/regular.js', {})
// @@include('files/sliders.js', {})
@@include('files/functions.js', {})
@@include('files/script.js', {})
@@include('files/map.js', {})
@@include('files/forms.js', {})
@@include('files/numberinsert.js', {})
@@include('files/aus.js', {})
// @@include('files/scroll.js', {})